name: Сборка Storybook
on:
  push:
    branches: [master]
  pull_request:

jobs:
  deploy:
    name: Сборка
    runs-on: ubuntu-latest

    steps:
      - name: Скачивание CSSSR actions
        uses: actions/checkout@v2
        with:
          repository: CSSSR/actions
          token: ${{ secrets.DOWNLOAD_ACTIONS_TOKEN }}
          path: actions

      - uses: actions/checkout@v2
        with:
          path: vega-ui

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: yarn install --frozen-lockfile
        working-directory: ./vega-ui

      - run: yarn build
        working-directory: './vega-ui'

      - run: yarn build-storybook
        working-directory: ./vega-ui

      - name: Загрузка статических файлов и деплой storybook
        uses: ./actions/deploy-static-site/v1beta1
        with:
          auth: ${{ secrets.CSSSR_AUTH }}
          project-id: vega-ui-storybook
          files: vega-ui/storybook-static
          token: ${{ secrets.GITHUB_TOKEN }}
